const userData = [
    {
        UserID: 1,
        FullName: 'Trần Nhật Danh',
        Position: 'Nhân viên',
        Room: '',
        Office: 'Tổng cục thống kê',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
    {
        UserID: 2,
        FullName: 'Trần Nhật Danh2',
        Position: 'Chuyên viên',
        Room: '',
        Office: 'Tổng cục đường sắt',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: false,
    },
    {
        UserID: 3,
        FullName: 'Trần Nhật Danh3',
        Position: 'Thử việc ',
        Room: '',
        Office: 'Tổng cục đường bộ',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
    {
        UserID: 4,
        FullName: 'Trần Nhật Danh',
        Position: 'Nhân viên',
        Room: '',
        Office: 'Tổng cục thống kê',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
    {
        UserID: 5,
        FullName: 'Trần Nhật Danh2',
        Position: 'Chuyên viên',
        Room: '',
        Office: 'Tổng cục đường sắt',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: false,
    },
    {
        UserID: 6,
        FullName: 'Trần Nhật Danh3',
        Position: 'Thử việc ',
        Room: '',
        Office: 'Tổng cục đường bộ',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
    {
        UserID: 7,
        FullName: 'Trần Nhật Danh',
        Position: 'Nhân viên',
        Room: '',
        Office: 'Tổng cục thống kê',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
    {
        UserID: 8,
        FullName: 'Trần Nhật Danh2',
        Position: 'Chuyên viên',
        Room: '',
        Office: 'Tổng cục đường sắt',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: false,
    },
    {
        UserID: 9,
        FullName: 'Trần Nhật Danh3',
        Position: 'Thử việc ',
        Room: '',
        Office: 'Tổng cục đường bộ',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
    {
        UserID: 10,
        FullName: 'Trần Nhật Danh',
        Position: 'Nhân viên',
        Room: '',
        Office: 'Tổng cục thống kê',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
    {
        UserID: 12,
        FullName: 'Trần Nhật Danh2',
        Position: 'Chuyên viên',
        Room: '',
        Office: 'Tổng cục đường sắt',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: false,
    },
    {
        UserID: 13,
        FullName: 'Trần Nhật Danh3',
        Position: 'Thử việc ',
        Room: '',
        Office: 'Tổng cục đường bộ',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
    {
        UserID: 14,
        FullName: 'Trần Nhật Danh',
        Position: 'Nhân viên',
        Room: '',
        Office: 'Tổng cục thống kê',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
    {
        UserID: 15,
        FullName: 'Trần Nhật Danh2',
        Position: 'Chuyên viên',
        Room: '',
        Office: 'Tổng cục đường sắt',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: false,
    },
    {
        UserID: 16,
        FullName: 'Trần Nhật Danh3',
        Position: 'Thử việc ',
        Room: '',
        Office: 'Tổng cục đường bộ',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
    {
        UserID: 17,
        FullName: 'Trần Nhật Danh',
        Position: 'Nhân viên',
        Room: '',
        Office: 'Tổng cục thống kê',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
    {
        UserID: 18,
        FullName: 'Trần Nhật Danh2',
        Position: 'Chuyên viên',
        Room: '',
        Office: 'Tổng cục đường sắt',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: false,
    },
    {
        UserID: 19,
        FullName: 'Trần Nhật Danh3',
        Position: 'Thử việc ',
        Room: '',
        Office: 'Tổng cục đường bộ',
        Email: 'trannhatdanh@gmail.com',
        Mobile: '0905884892',
        OfficalMobile: '0905884892',
        UserGroup:
            'Cán bộ thuộc đơn vị hành chính (trừ Cục thu thập), Lãnh đạo Tổng cục phê duyệt đề nghị công tác, Tiếp nhận đề nghị đi công tác, Tổng cục trưởng phê duyệt đề nghị công tác',
        StatusWork: true,
    },
];

export default userData;
